<#
.SYNOPSIS
  Sets up a freshly flashed Thingino camera for Home Assistant (MQTT auto-discovery).

.DESCRIPTION
  Run from Windows PowerShell:   .\install.ps1
  or non-interactively:          .\install.ps1 -CameraIp 192.168.0.71

  Steps performed:
    1. Copies your SSH public key to the camera (ssh-copy-id, optional)
    2. Uploads thingino-ha-discovery.sh to the camera
    3. Configures on the camera: MQTT subscriber (<hostname>/cmd), motion -> MQTT,
       autostart of the discovery at boot, and runs the discovery once
    4. Verifies that the discovery payloads arrived at the broker

  Requirements: Windows OpenSSH client (ssh.exe), thingino-ha-discovery.sh next to this file.
  The camera must run a Thingino firmware with the prudynt streamer (prudyntctl).
#>
param(
    [string]$CameraIp,
    [string]$CameraUser = "root",
    [string]$Broker     = "192.168.0.48",
    [string]$Port       = "1883",
    [string]$MqttUser   = "thingino",
    [string]$MqttPass   = "thingino",
    [switch]$SkipKeyCopy,
    [switch]$NonInteractive
)

$ErrorActionPreference = "Continue"
$SSH = Join-Path $env:SystemRoot "System32\OpenSSH\ssh.exe"
if (-not (Test-Path $SSH)) { $SSH = "ssh" }

function Write-Step($msg) { Write-Host ""; Write-Host "==> $msg" -ForegroundColor Green }
function Fail($msg)       { Write-Host "ERROR: $msg" -ForegroundColor Red; exit 1 }

Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Thingino -> Home Assistant camera setup"   -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$DISCOVERY_SCRIPT = Join-Path $SCRIPT_DIR "thingino-ha-discovery.sh"
if (-not (Test-Path $DISCOVERY_SCRIPT)) { Fail "thingino-ha-discovery.sh not found next to install.ps1" }

# ---------- Inputs ----------
if (-not $CameraIp) { $CameraIp = Read-Host "Camera IP" }
if (-not $CameraIp) { Fail "no camera IP given" }

if (-not $NonInteractive) {
    $in = Read-Host "Camera SSH user [$CameraUser]";   if ($in) { $CameraUser = $in }
    $in = Read-Host "MQTT broker IP [$Broker]";        if ($in) { $Broker = $in }
    $in = Read-Host "MQTT port [$Port]";               if ($in) { $Port = $in }
    $in = Read-Host "MQTT username [$MqttUser]";       if ($in) { $MqttUser = $in }
    $in = Read-Host "MQTT password [$MqttPass]";       if ($in) { $MqttPass = $in }
}

foreach ($v in @($Broker, $MqttUser, $MqttPass)) {
    if ($v -match '["\\'']') { Fail "double quotes, backslashes and single quotes are not supported in broker/user/password" }
}

Write-Host ""
Write-Host "  Camera : ${CameraUser}@${CameraIp}"
Write-Host "  Broker : ${Broker}:${Port} (user $MqttUser)"
if (-not $NonInteractive) {
    $c = Read-Host "Apply? [y/N]"
    if ($c -notin @("y", "Y")) { Write-Host "Aborted."; exit 1 }
}

$Target  = "${CameraUser}@${CameraIp}"
$SshOpts = @("-o", "StrictHostKeyChecking=accept-new", "-o", "ConnectTimeout=10")

function Test-KeyLogin {
    $out = & $SSH @SshOpts -o BatchMode=yes $Target "echo KEY_OK" 2>$null
    return ($out -match "KEY_OK")
}

# ---------- Step 1: SSH key ----------
Write-Step "[1/4] SSH access"
if (Test-KeyLogin) {
    Write-Host "Key-based login works."
} elseif ($SkipKeyCopy) {
    Write-Host "No key login; you will be asked for the camera password on every step." -ForegroundColor Yellow
} else {
    $copyId = Get-Command ssh-copy-id -ErrorAction SilentlyContinue
    if ($copyId) {
        Write-Host "Copying your SSH public key to the camera (enter the camera's root password once)..."
        & ssh-copy-id -o StrictHostKeyChecking=accept-new $Target
        if (Test-KeyLogin) { Write-Host "Key-based login works now." }
        else { Write-Host "Key copy did not work; continuing with password prompts." -ForegroundColor Yellow }
    } else {
        Write-Host "ssh-copy-id not found; continuing with password prompts (or add your key in the Thingino WebUI)." -ForegroundColor Yellow
    }
}

# ---------- Step 2: upload discovery script ----------
Write-Step "[2/4] Uploading thingino-ha-discovery.sh"
# 'tr -d' strips any CR that PowerShell adds when piping to a native command.
$content = [System.IO.File]::ReadAllText($DISCOVERY_SCRIPT)
$content | & $SSH @SshOpts $Target "tr -d '\r' > /usr/sbin/thingino-ha-discovery.sh && chmod +x /usr/sbin/thingino-ha-discovery.sh && echo UPLOAD_OK"
if ($LASTEXITCODE -ne 0) { Fail "upload failed" }

# ---------- Step 3: configure camera ----------
Write-Step "[3/4] Configuring the camera"

$SETUP = @'
#!/bin/sh
# Generated by install.ps1 - runs on the camera
TOKEN=$(cat /etc/thingino-api.key 2>/dev/null)
HOST=$(hostname)
fail() { echo "ERROR: $1" >&2; exit 1; }
api() {
	# $1 = cgi name, $2 = JSON body; prints response, fails on HTTP error
	curl -sf -X POST "http://localhost/x/$1?token=$TOKEN" -H "Content-Type: application/json" -d "$2"
}

command -v prudyntctl >/dev/null 2>&1 || fail "prudyntctl not found - this firmware does not use the prudynt streamer"
command -v mosquitto_pub >/dev/null 2>&1 || fail "mosquitto_pub not found on the camera"
[ -n "$TOKEN" ] || fail "/etc/thingino-api.key missing"

echo "--- MQTT subscriber (commands from HA on $HOST/cmd) ---"
api json-config-mqtt-sub.cgi '{"enabled":true,"host":"__BROKER__","port":__PORT__,"username":"__USER__","password":"__PASS__","use_ssl":false,"subscriptions":[{"topic":"%hostname/cmd","qos":0,"action":"eval $MQTT_PAYLOAD","enabled":true}]}' >/dev/null \
	|| fail "json-config-mqtt-sub.cgi failed"
[ "$(jct /etc/thingino.json get mqtt_sub.host | tr -d '"')" = "__BROKER__" ] || fail "mqtt_sub config was not saved"

echo "--- Disable logo OSD (persist prudynt's current config first) ---"
# save_config dumps prudynt's in-memory config to /etc/prudynt.json, so this
# must happen BEFORE the motion settings are written into that file below.
printf '{"stream0":{"osd":{"logo":{"enabled":false}}},"stream1":{"osd":{"logo":{"enabled":false}}},"action":{"save_config":null}}' | prudyntctl json - >/dev/null 2>&1
sleep 1

echo "--- Motion events -> MQTT ($HOST/motion) ---"
api json-config-send2.cgi '{"config":{"mqtt":{"enabled":true,"host":"__BROKER__","port":__PORT__,"username":"__USER__","password":"__PASS__","use_ssl":false,"client_id":"'"$HOST"'","topic":"'"$HOST"'/motion","message":"{\"timestamp\": \"%s\"}","send_photo":false,"topic_photo":""}}}' >/dev/null \
	|| fail "json-config-send2.cgi (mqtt) failed"

# Motion detection is written to /etc/prudynt.json and activated by restarting
# prudynt. Enabling it live on a fresh camera crashes prudynt (detection frame
# 0x0), so the frame is set to the main stream size here.
W=$(jct /etc/prudynt.json get stream0.width 2>/dev/null); H=$(jct /etc/prudynt.json get stream0.height 2>/dev/null)
W=${W:-1920}; H=${H:-1080}
for kv in "enabled true" "send2mqtt true" "frame_width $W" "frame_height $H" "roi_count 1" "roi_0_x 0" "roi_0_y 0" "roi_1_x $((W - 1))" "roi_1_y $((H - 1))"; do
	jct /etc/prudynt.json set "motion.${kv% *}" "${kv#* }" >/dev/null || fail "cannot write motion.${kv% *}"
done
echo "--- Restart prudynt to apply motion settings ---"
/etc/init.d/S31prudynt restart >/dev/null 2>&1
n=0
while [ ! -S /run/prudynt/prudynt.sock ] || ! pidof prudynt >/dev/null 2>&1; do
	n=$((n + 1)); [ $n -ge 30 ] && fail "prudynt did not come back after restart"
	sleep 1
done
sleep 3
pidof prudynt >/dev/null 2>&1 || fail "prudynt crashed after restart (see logread)"

echo "--- Restart MQTT subscriber ---"
# S91mqttsub stop only kills the dispatcher shell; its mosquitto_sub child would
# survive and execute every command a second time. Kill only the dispatcher's
# subscriber (the official ha-daemon runs its own mosquitto_sub, leave that alone).
/etc/init.d/S91mqttsub stop >/dev/null 2>&1
killall mqtt-sub-dispatcher 2>/dev/null
pkill -f "mosquitto_sub.* -t $HOST/cmd" 2>/dev/null
sleep 1
/etc/init.d/S91mqttsub start
sleep 2
[ "$(ps w | grep -c "[m]osquitto_sub.* -t $HOST/cmd")" = "1" ] || fail "MQTT command subscriber not running exactly once (broker unreachable?)"

echo "--- Autostart discovery at boot ---"
cat > /etc/init.d/S99ha-discovery <<'EOF'
#!/bin/sh
case "$1" in
	start) /usr/sbin/thingino-ha-discovery.sh > /tmp/ha-discovery.log 2>&1 & ;;
esac
EOF
chmod +x /etc/init.d/S99ha-discovery

echo "--- Running HA discovery ---"
/usr/sbin/thingino-ha-discovery.sh || fail "discovery failed"

echo "--- Verifying retained discovery config at the broker ---"
if mosquitto_sub -h "__BROKER__" -p __PORT__ -u "__USER__" -P "__PASS__" -t "homeassistant/switch/${HOST}_privacy/config" -C 1 -W 5 >/dev/null 2>&1; then
	echo "OK: discovery payloads are stored at the broker"
else
	fail "discovery payload not found at the broker"
fi
echo "SETUP_OK"
'@

$SETUP = $SETUP.Replace("__BROKER__", $Broker).Replace("__PORT__", $Port).Replace("__USER__", $MqttUser).Replace("__PASS__", $MqttPass)
$SETUP | & $SSH @SshOpts $Target "tr -d '\r' > /tmp/thingino-setup.sh && sh /tmp/thingino-setup.sh"
if ($LASTEXITCODE -ne 0) { Fail "camera setup failed (see output above)" }

# ---------- Step 4: summary ----------
Write-Step "[4/4] Done"
Write-Host "The camera should now appear in Home Assistant under Settings -> Devices (MQTT)." -ForegroundColor Cyan
Write-Host "Log of the boot-time discovery on the camera: /tmp/ha-discovery.log"
